name: Team awesome's approval workflow
on: pull_request_review
jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    steps:
      - uses: label-when-approved-action
      - name: run label whem approved
        env:
          APPROVALS: '1'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: 'APPROVED'
