
name: Node CI

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: npm install and build
        run: |
          npm install
          npm run build
          
    test:
      - uses: actions/upload-artifact@master
        with:
        needs: build
        path: public/
        strategy:
          matrix:
            node-version: [12.x]
        steps:
        - uses: actions/checkout@v2     
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - name: npm install, build, and test
          run: |
            npm install
            npm run lint
            npm run build:test && npm run start:test
            npm run build:e2e && npm run start:e2e
          env:
            CI: true
